### ISSUE TITLE
ImportError: No module named _gdal_array

### ISSUE THREAD

**Issue by simgislab** [nextgis-borsch/lib_gdal#17]
<<< C:\Users\Admin\Desktop\new>SET PATH=C:\NextGIS\bin;C:\NextGIS\bin;C:\Python\Scripts\;C:\Python\;C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;

C:\Users\Admin\Desktop\new>python
Python 2.7.12 (default, May 18 2017, 02:50:23) [MSC v.1800 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z

C:\Users\Admin\Desktop\new>gdal_merge.py -o outputALL.tif output111.tif output222.tif -separate
0Traceback (most recent call last):
  File "C:\NextGIS\bin\gdal_merge.py", line 540, in 
    sys.exit(main())
  File "C:\NextGIS\bin\gdal_merge.py", line 529, in main
    fi.copy_into( t_fh, band, t_band, nodata )
  File "C:\NextGIS\bin\gdal_merge.py", line 270, in copy_into
    nodata_arg )
  File "C:\NextGIS\bin\gdal_merge.py", line 77, in raster_copy
    m_band )
  File "C:\NextGIS\bin\gdal_merge.py", line 125, in raster_copy_with_mask
    t_xsize, t_ysize )
  File "C:\NextGIS\Lib\python27\site-packages\osgeo\gdal.py", line 2528, in ReadAsArray
    import gdalnumeric
  File "C:\NextGIS\Lib\python27\site-packages\osgeo\gdalnumeric.py", line 1, in 
    from osgeo.gdal_array import *
  File "C:\NextGIS\Lib\python27\site-packages\osgeo\gdal_array.py", line 28, in 
    _gdal_array = swig_import_helper()
  File "C:\NextGIS\Lib\python27\site-packages\osgeo\gdal_array.py", line 20, in swig_import_helper
    import _gdal_array
ImportError: No module named _gdal_array

**Comment by alisovenko** [comment]
Видимо, это отсутствие numpy при сборке bindings:
https://github.com/nextgis-borsch/lib_gdal/blob/master/bindings/python/setup.py#L279-L281

**Comment by simgislab** [comment]
@alisovenko закрываем?

**Comment by BishopGIS** [comment]
Если что переоткроете
